'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user
    Public Property id As Integer
    Public Property uid As String
    Public Property email As String
    Public Property full_name As String
    Public Property password As String
    Public Property profile_img As String
    Public Property user_status As String

End Class
